// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	PasswordHsh string           `json:"password_hsh"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
